language: go
branches:
  only:
  - master
cache:
  directories:
  - vendor
sudo: required
services:
- docker
install:
- make bootstrap
script:
- make build-docker test-docker
notifications:
  slack:
    secure: seJNLugEhd/KbmbwaYItywTFfRN6fNpXTn8DumH00/Xik826gTf/vZfjZ7hvfCZ/ai9ozXbpScdr/+qEv6lQAYcUIh3gbjah23Avh9sjsXtEAPSd40RdDwqKVPUNHzUFlc8N4dxkQqtgEEAKkVM5DLyvzagn2p0rgjxV2HqQ8muk9WDexjTLO9UZJtDH1V9IB57jEqRvUuX5aa7yfFXIZUBsOkJB4eO+76RoeU78HPSr/T1eqQ0u/pn5L5eoAponS0XCg4ldVxDSNZ6OL8jA6V3HL64NqcHnAy0giZCeIhZCuYR7+EOMdVnQdl2L+KcrVoBXUEqAXRyX7FzJtGdC1TOljr9hfeSXvDDh3ZqcED0ZSZETeGKgDVnAQnLXA3684N9LSQ7GxUuwJorr/e0++Sk48rHCJfJMRNiJtsmpOGo5e3EogBgLLjaUgKPK/pvnbnjdiXCXsWjy2OrHodJ20dpjm+dRO2cEZj0Z4vHcPvByumgbxxfPJz47gS1Kw7XvFgnPUElBQcM6dKkjmQVFv7NckPHJncyO8+ZIif8TsghTUr31cEyx6ClmLhZryDS8Pkrls2HobYEVw9lAg2AFm0RC+bh2AmJfVjDGhcreSyeaqE1hP3Ie8gF1w5GP2Gskc3/g2wquZQrthVOr1aww1UEsg5U7SzdTij17W8AoloQ=
